name: Terraform Apply

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

env:
  TF_CLOUD_ORGANIZATION: "MavoyanCapstoneProject"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "capstone-project-terraform-github-actions"
  CONFIG_DIRECTORY: "./"

jobs:
  terraform:
    runs-on: ubuntu-latest
    name: Terraform Apply
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload Configuration to Terraform Cloud
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
        id: upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.CONFIG_DIRECTORY }}
          speculative: false  

      - name: Create Run 
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.upload.outputs.configuration_version_id }}
          plan_only: false  
