name: Apply

on:
  push:
    branches:
      - main
env:
  TF_CLOUD_ORGANIZATION: "MavoyanCapstoneProject"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "capstone-project-terraform-github-actions"
  CONFIG_DIRECTORY: "./"

permissions:
  contents: read
  pull-requests: write

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Apply plan
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: .